
artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: inception_ct.h5
  UPDATED_BASE_MODEL_NAME: updated_inception_ct.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks
  DATA_DIR: Artifacts/raw_data/ct_scan/

source_download_dirs:
  - ../outside_data/CT_COVID/
  - ../outside_data/CT_NonCOVID/

local_data_dirs:
  - Artifacts/raw_data/ct_scan/CT_COVID
  - Artifacts/raw_data/ct_scan/CT_NonCOVID