
artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: inception_ct.h5
  UPDATED_BASE_MODEL_NAME: updated_inception_ct.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks
<<<<<<< HEAD
  DATA_DIR: Artifacts/raw_data/ct_scan

source_download_dirs:
  - ../outside_data/raw_data_medical_image_processing/chest-x-ray
  - ../outside_data/raw_data_medical_image_processing/ct_scan
  
=======
  DATA_DIR: Artifacts/raw_data/ct_scan/

source_download_dirs:
  - ../outside_data/raw_data_medical_image_processing/chest-x-ray/Chest_COVID/
  - ../outside_data/raw_data_medical_image_processing/chest-x-ray/Chest_NonCOVID/
  - ../outside_data/raw_data_medical_image_processing/ct_scan/CT_COVID/
  - ../outside_data/raw_data_medical_image_processing/ct_scan/CT_NonCOVID/

>>>>>>> 50a41d59c3f55f5f0650d6254db9a3e6ad232c5f
local_data_dirs:
  - Artifacts/raw_data/chest-x-ray/Chest_COVID
  - Artifacts/raw_data/chest-x-ray/Chest_NonCOVID
  - Artifacts/raw_data/ct_scan/CT_COVID
  - Artifacts/raw_data/ct_scan/CT_NonCOVID